version: '3.1'

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
#    network_mode: "host"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
#    network_mode: "host"

  tgbot:
    container_name: bot
    build: 
      context: .
    volumes:
      - .:/src
    command: .py3env/bin/python app.py
    restart: always
    network_mode: "host"

    env_file:
      - ".env"

volumes:
  database-data: # named volumes can be managed easier using docker-compose